### ISSUE TITLE
_cliser_read/write function are missing 

### ISSUE THREAD

**Issue by yuntang** [twitter/torch-ipc#5]
I tried to repeat the client-server.sh experiment in the example directory. 
It works without modification, e.g. passing FloatTensor between different CPUs within one machine.
Then I modify the script to pass CudaTensor 

>   # run a server
> export CUDA_VISIBLE_DEVICES=2
>  th client-server.lua --server 1   --cuda&
>  # run 1 client 
> export CUDA_VISIBLE_DEVICES=3
>  th client-server.lua -n 1 --cuda   &
> wait

The program is broken with errors below:

> loading cutorch...	
> loading cutorch...	
> cutorch loaded ok.	
> cutorch loaded ok.	
> /home/yun_tang/torch/install/bin/luajit: client-server.lua:57: ERROR: (/home/yun_tang/tmp/torch-ipc-master/src/cliser.c, 538): (could not find _cliser_write function in meltable)

> 
> stack traceback:
> 	[C]: in function 'send'
> 	client-server.lua:57: in function <client-server.lua:55>
> 	[C]: in function 'clients'
> 	client-server.lua:55: in main chunk
> 	[C]: in function 'docile'
> 	...tang/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
> 	[C]: at 0x00405800
> /home/yun_tang/torch/install/bin/luajit: client-server.lua:90: ERROR: (/home/yun_tang/tmp/torch-ipc-master/src/cliser.c, 552): (could not find _cliser_read function in meltable)

> 
> stack traceback:
> 	[C]: in function 'recv'
> 	client-server.lua:90: in main chunk
> 	[C]: in function 'docile'
> 	...tang/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
> 	[C]: at 0x00405800

Is there any component I missed?
Also, is there any plan for examples used in different machines (torch-ipc and torch-distlearn)

Thanks

Yun

**Comment by zakattacktwitter** [comment]
Hi,

My apologies for this, but when building torch-ipc you need to specify a CUDA=YES flag.

> cd torch-ipc
> CUDA=YES luarocks make

This is an artifact of our internal build system leaking out into the open source. I will fix it soon, until then simply rebuilding it should work.

Yes, there are definitely plans for more examples. There are two main blockers though.

First, it has been hard to find a big public dataset that warrants using distributed learning. MNIST and CIFAR are really small datasets, there's little point in distributing their training. If you know of a big public dataset that would benefit please let me know. IMGNET would be cool but the license prevents me from using it (non-commercial or educational only).

Second, we want to provide an example using AWS GPU machines. Its not ideal as those machines are not capable of doing GPU to GPU communications using IPC, due to a limitation of the Citrix virtualization layer. We still might use them for an example, but it would not be used as a performance benchmark.

Stay tuned!

Thanks,
Zak

**Comment by zakattacktwitter** [comment]
This commit b9599e46919d952b3c4af8c90141a618e2219df4 will fix the need to state CUDA=YES and it will do better checking if the GPUs are truly peers.

**Comment by yuntang** [comment]
It works..
Can the multiple-machines example be tested on the billionwords LM task?
https://github.com/nicholas-leonard/dp/blob/master/data/billionwords.lua
Thanks

Yun
